-- Kanagawa -- GENERATED by `theme`
return {
	name = "Kanagawa",
	bg = "#1f1f28",
	bg_dark = "#16161d",
	fg = "#dcd7ba",
	dim = "#c8c093",
	muted = "#727169",
	sel = "#363646",
	accent = "#ffa066",
	accent2 = "#7e9cd8",
	red = "#c34043",
	green = "#98bb6c",
	yellow = "#e6c384",
	blue = "#7e9cd8",
	magenta = "#957fb8",
	cyan = "#7aa89f",
}
