-- @@name@@ -- GENERATED by `theme`; edit themes/templates/hypr-colors.lua instead
hl.config({
	general = {
		col = {
			active_border = { colors = { "rgba(@@border_active1@@ee)", "rgba(@@border_active2@@ee)" }, angle = 45 },
			inactive_border = "rgba(@@border_inactive@@aa)",
		},
	},
})
