-- @@name@@ -- GENERATED by `theme`
return {
	name = "@@name@@",
	bg = "@@bg@@",
	bg_dark = "@@bg_dark@@",
	fg = "@@fg@@",
	dim = "@@dim@@",
	muted = "@@muted@@",
	sel = "@@sel@@",
	accent = "@@accent@@",
	accent2 = "@@accent2@@",
	red = "@@red@@",
	green = "@@green@@",
	yellow = "@@yellow@@",
	blue = "@@blue@@",
	magenta = "@@magenta@@",
	cyan = "@@cyan@@",
}
