-- Kanagawa -- GENERATED by `theme`; edit themes/templates/hypr-colors.lua instead
hl.config({
	general = {
		col = {
			active_border = { colors = { "rgba(d27e99ee)", "rgba(7e9cd8ee)" }, angle = 45 },
			inactive_border = "rgba(363646aa)",
		},
	},
})
