-- Generated by nwg-displays on 2026-08-28 at 12:26:14. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2240x1400@60.0",
    position = "3840x120",
    scale = 1.4583334
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1920x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0
})
