name=Dracula
bg=#282a36
bg_alpha=f0
bg_dark=#21222c
fg=#f8f8f2
dim=#bfbfd4
muted=#6272a4
sel=#44475a
accent=#ffb86c
accent2=#bd93f9
red=#ff5555
green=#50fa7b
yellow=#f1fa8c
blue=#8be9fd
magenta=#ff79c6
cyan=#8be9fd
border_active1=bd93f9
border_active2=ff79c6
border_inactive=44475a
wallpaper=generated/dracula.png
nvim_colorscheme=dracula
