name=Everforest
bg=#2d353b
bg_alpha=f2
bg_dark=#232a2e
fg=#d3c6aa
dim=#9da9a0
muted=#859289
sel=#3d484d
accent=#e69875
accent2=#a7c080
red=#e67e80
green=#a7c080
yellow=#dbbc7f
blue=#7fbbb3
magenta=#d699b6
cyan=#83c092
border_active1=a7c080
border_active2=7fbbb3
border_inactive=4f585e
wallpaper=generated/everforest.png
nvim_colorscheme=everforest
