name=Nord
bg=#2e3440
bg_alpha=f2
bg_dark=#242933
fg=#eceff4
dim=#d8dee9
muted=#4c566a
sel=#434c5e
accent=#d08770
accent2=#88c0d0
red=#bf616a
green=#a3be8c
yellow=#ebcb8b
blue=#81a1c1
magenta=#b48ead
cyan=#8fbcbb
border_active1=88c0d0
border_active2=b48ead
border_inactive=4c566a
wallpaper=generated/nord.png
nvim_colorscheme=nord
