name=Synthwave
bg=#241b2f
bg_alpha=f0
bg_dark=#1a1526
fg=#f0eff1
dim=#b6b1b8
muted=#7c709a
sel=#463465
accent=#ff7edb
accent2=#36f9f6
red=#fe4450
green=#72f1b8
yellow=#fede5d
blue=#36f9f6
magenta=#ff7edb
cyan=#36f9f6
border_active1=ff2e97
border_active2=36f9f6
border_inactive=463465
wallpaper=generated/synthwave.png
nvim_colorscheme=tokyonight-night
